export const country =  [
     	

       {city:"Tunis-Tunis"},
       {city:"Tunis-Sfax"},
       {city:"Tunis-Sousse"},
       {city: "Tunis-Gabès"},
       {city:"Tunis-Zarzis"},
       {city: "Tunis-Qairouan"},
       {city: "Tunis-Bizerte"},
       {city: "Tunis-Gafsa"},
       {city: "Tunis-Nabeul"},
       {city: "Tunis-L'Ariana"},
       {city: "Tunis-Qasserine"},
       {city: "Tunis-Monastir"},
       {city: "Tunis-Tataouine"},
       {city: "Tunis-Medenine"},
       {city: "Tunis-Béja"},
       {city: "Tunis-Jendouba"},
       {city: "France-Paris"},
       {city: "France-Lyon"},	
       {city: "France-Marseille"},	
       {city: "France-Lille"},	
       {city: "France-Nice"},	
       {city: "France-Toulouse"},	
       {city: "France-Bordeaux"},
       {city: "France-Rouen"},	
       {city: "France-Strasbourg"},
       {city: "France-Nantes"},
       {city: "France-Metz"},	
       {city: "France-Grenoble"},	
       {city: "France-Toulon"},	
       {city: "France-Montpellier"},	
       {city: "France-Nancy"},	
       {city: "France-Saint-Étienne"},	
       {city: "France-Fort-de-France"},	
       {city: "France-Melun"},	
       {city: "France-Le Havre"},	
       {city: "France-Tours"},	
       {city: "France-Clermont-Ferrand"},	
       {city: "France-Orléans"},	
       {city: "France-Mulhouse"},	
       {city: "France-Rennes"},	
       {city: "France-Reims"},	
       {city: "France-Caen"},	
       {city: "France-Angers"},
       {city: "France-Dijon"},	
       {city: "France-Nîmes"},	
       {city: "France-Limoges"},	
       {city: "France-Aix-en-Provence"},	
       {city: "France-Perpignan"},
       {city: "France-Biarritz"},	
       {city: "France-Brest"},	
       {city: "France-Le Mans"},	
       {city: "France-Amiens"},
       {city: "France-Besançon"},	
       {city: "France-Annecy"},	
       {city: "France-Calais"},
       {city: "France-Poitier"},	
       {city: "France-Versailles"},	
       {city: "France-Lorient"},	
       {city: "France-Béziers"},	
       {city: "France-La Rochelle"},	
       {city: "France-Roanne"},	
       {city: "France-Bourges"},	
       {city: "France-Arras"},	
       {city: "France-Troyes"},	
       {city: "France-Cherbourg"},
       {city: "France-Agen"},	
       {city: "France-Brive"},	
       {city: "France-Tarbes"},	
       {city: "France-Ajaccio"},	
       {city: "France-St.-Brieuc"},	
       






    ];




